<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('bixo_product_properties', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('organization_id')->nullable()->index();
            $table->unsignedBigInteger('branch_id')->nullable()->index();
            $table->unsignedBigInteger('department_id')->nullable()->index();
            $table->unsignedBigInteger('division_id')->nullable()->index();
            $table->unsignedBigInteger('subdivision_id')->nullable();
            $table->unsignedBigInteger('contact_id')->nullable()->index();
            $table->unsignedBigInteger('developer_id')->nullable();
            $table->unsignedBigInteger('country_id')->nullable()->index();
            $table->unsignedBigInteger('region_id')->default(4)->index();
            $table->unsignedBigInteger('location_id')->nullable()->index();
            $table->unsignedBigInteger('sublocation_id')->nullable()->index();
            $table->unsignedBigInteger('building_id')->nullable()->index();
            $table->unsignedBigInteger('tower_id')->nullable()->index();
            $table->unsignedBigInteger('building_no_id')->nullable();
            $table->string('tower_name', 100)->nullable();
            $table->enum('category_type', ['Commercial', 'Residential'])->default('Residential')->index();
            $table->string('category', 30)->nullable()->index();
            $table->enum('property_for', ['Rental', 'Sales'])->nullable()->index();
            $table->enum('property_type', ['Live', 'Pocket', 'Developer', 'Verified Pocket'])->nullable()->index();
            $table->enum('status', ['Draft', 'Pending', 'Waiting Publish', 'Published', 'Waiting Unpublish', 'Unpublished', 'Archived', 'Approved', 'Rejected', 'Pocket Publish', 'Pending Verification', 'Verified', 'Completed', 'Public', 'Private', 'Junk', 'Waiting Teamleader', 'Waiting Team Leader'])->default('Draft')->index();
            $table->string('property_status', 50)->nullable()->index();
            $table->boolean('premium')->nullable();
            $table->boolean('exclusive')->default(0)->index();
            $table->string('title', 100)->nullable()->index();
            $table->string('ref', 100)->nullable()->index();
            $table->string('ref_old', 50)->nullable();
            $table->string('ref_pf', 50)->nullable()->index();
            $table->string('ref_byt', 100)->nullable()->index();
            $table->string('unit', 20)->nullable()->index();
            $table->string('type', 25)->nullable();
            $table->string('floor', 30)->nullable();
            $table->string('beds', 50)->nullable()->index();
            $table->integer('baths')->nullable()->index();
            $table->integer('parking')->nullable()->index();
            $table->decimal('bua', 10, 2)->nullable()->index();
            $table->bigInteger('price')->nullable()->index();
            $table->bigInteger('service_charge')->nullable();
            $table->text('description')->nullable();
            $table->longText('description_more')->nullable();
            $table->enum('construction_status', ['Completed', 'Under Construction'])->nullable();
            $table->date('completion_on')->nullable();
            $table->enum('furnishing', ['Furnished', 'Unfurnished', 'Partly Furnished', 'Fitted', 'Not Fitted', 'Shell And Core'])->nullable()->index();
            $table->enum('appliances', ['Included', 'Not Included'])->nullable();
            $table->text('views')->nullable();
            $table->string('plot', 10)->nullable();
            $table->boolean('price_on_request')->default(0);
            $table->enum('lease_term', ['Day', 'Week', 'Month', 'Year', ''])->nullable();
            $table->tinyInteger('cheques')->nullable();
            $table->string('street_no', 200)->nullable();
            $table->string('parking_no', 20)->nullable();
            $table->longText('photos')->nullable();
            $table->text('floor_plans')->nullable();
            $table->decimal('conmmission_split', 5, 2)->nullable();
            $table->float('deposit', 5, 2)->nullable();
            $table->float('deposit_amount', 14, 2)->nullable();
            $table->text('portals')->nullable();
            $table->text('portals_data')->nullable();
            $table->text('medias')->nullable();
            $table->text('features')->nullable();
            $table->text('features_temp')->nullable();
            $table->text('amenities_temp')->nullable();
            $table->text('features_intl_temp')->nullable();
            $table->date('available_from')->nullable();
            $table->boolean('rented')->default(0);
            $table->bigInteger('rented_price')->nullable();
            $table->tinyInteger('rented_cheques')->nullable();
            $table->date('rent_start')->nullable();
            $table->date('rent_end')->nullable();
            $table->string('trakheesi', 255)->nullable();
            $table->string('permit_period', 100)->nullable();
            $table->string('trakheesi_branch', 30)->nullable();
            $table->enum('is_verify', ['Yes', 'No', 'Pending'])->default('No');
            $table->string('payment_plan', 200)->nullable();
            $table->string('selling_reason', 255)->nullable();
            $table->date('form_a_expiry')->nullable();
            $table->string('next_investment_plan', 255)->nullable();
            $table->string('project', 200)->nullable();
            $table->unsignedBigInteger('project_id')->nullable();
            $table->text('portal_settings')->nullable();
            $table->text('settings')->nullable();
            $table->string('latitude', 50)->nullable()->index();
            $table->string('longitude', 50)->nullable()->index();
            $table->text('notes')->nullable();
            $table->string('str', 100)->nullable();
            $table->tinyInteger('company_listing')->default(0);
            $table->text('documents')->nullable();
            $table->text('public_documents')->nullable();
            $table->string('upload_folder', 100)->nullable();
            $table->string('listing_source', 100)->nullable();
            $table->text('dld_details')->nullable();
            $table->string('dld_status', 50)->nullable();
            $table->dateTime('dld_checked_at')->nullable();
            $table->enum('frequency', ['yearly', 'monthly', 'weekly', 'daily'])->default('yearly');
            $table->unsignedBigInteger('pf_id')->nullable();
            $table->unsignedBigInteger('user_id')->nullable()->index();
            $table->string('user_type', 50)->nullable();
            $table->unsignedBigInteger('published_by')->nullable();
            $table->unsignedBigInteger('assign_to')->nullable()->index();
            $table->longText('updates')->nullable();
            $table->text('feature_tags')->nullable();
            $table->text('feature_tags_temp')->nullable();
            $table->tinyInteger('watermark')->default(1);
            $table->dateTime('activated_at')->nullable();
            $table->unsignedBigInteger('referred_by')->nullable();
            $table->decimal('referral_pct', 10, 2)->nullable();
            $table->unsignedBigInteger('marketed_by')->nullable()->index();
            $table->unsignedBigInteger('created_by')->default(1)->index();
            $table->tinyInteger('lead_auto_assign')->default(0);
            $table->dateTime('trakheesi_expiry')->nullable();
            $table->tinyInteger('pf_subpermit')->default(0);
            $table->dateTime('published_at')->nullable()->index();
            $table->dateTime('unpublished_at')->nullable();
            $table->string('unpublish_reason', 140)->nullable();
            $table->text('report')->nullable();
            $table->timestamp('user_updated_at')->nullable();
            $table->timestamp('notified_at')->nullable();
            $table->dateTime('payment_date')->nullable();
            $table->dateTime('expires_at')->nullable();
            $table->dateTime('handover_date')->nullable();
            $table->text('portal_data')->nullable();
            $table->timestamp('synced_at')->nullable()->useCurrent();
            $table->timestamps();
            $table->dateTime('archived_at')->nullable();
            $table->softDeletes();
            $table->dateTime('contract_end')->nullable();
            $table->string('status_temp', 50)->nullable();
            $table->unsignedBigInteger('category_id_temp')->nullable();
            $table->text('temp_dld_data')->nullable();
            $table->text('temp_dld_details')->nullable();
            $table->dateTime('temp_sync_at')->default('2025-06-11 10:10:10');
            $table->text('temp_public_documents')->nullable();
            $table->dateTime('temp_expiry_at')->nullable();
            $table->bigInteger('original_price')->nullable();
            $table->index(['deleted_at']);
        });
    }
    public function down(): void
    {
        Schema::dropIfExists('bixo_product_properties');
    }
};
